### ISSUE TITLE
jadwal tidak sesuai untuk kota sumedang

### ISSUE THREAD

**Issue by nanaperm12** [myquran-com/iMasjid#1]
apa yg harus diperbaiki jadwalnya tidak sesuai, dan gimana caranya tanpa menggunakan fitur koreksi

**Comment by nanaperm12** [comment]
saya tes dilokal, apa harus di hoting ?

**Comment by banghasan** [comment]
coba ditunjukkan datanya

**Comment by banghasan** [comment]
==tidak ada tanggapan==
